### ISSUE TITLE
Support installation with composer

### ISSUE THREAD

**Issue by mvachette** [pce/config_lite#6]
I will be great to be able to support installation using composer, directly from github sources, especially bcause pear package seems to be broken

**Comment by Hackmodford** [comment]
+1 I just tried doing this using the guide on the readme with no luck :(

**Comment by alasdaircr** [comment]
The guide is wrong, you need to insert this instead:

```
"repositories": [
        {
            "type": "pear",
            "url": "pear.php.net"
        }
],
"require": {
	"pear-pear.php.net/config_lite": "*"
}
```

Note `pear-pear.php.net/config_lite`

**Comment by edbizarro** [comment]
@alasdaircr :+1:

**Comment by Hackmodford** [comment]
Perfect Thanks :)

**Comment by raknjak** [comment]
Just a note, please use explicit SSL like
"url": "https://pear.php.net" 
as secure-http defaults to true in modern composer versions.
